name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install archive tools
        uses: sudo apt install zip

      - name: Bundle files
        run: |
          mkdir -p ./temp/mongodb
          cp ./{LICENSE,README.md,fxmanifest.lua} ./temp/mongodb
          cp -r ./dist ./temp/mongodb
          cd ./temp && zip -r ../mongodb.zip ./mongodb

      - name: Save the build
        uses: actions/upload-artifact@main
        with:
          name: mongodb
          path: mongodb.zip