name: Build Project

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install archive tools
      run: sudo apt install zip

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.repository.default_branch }}

    - name: Get variables
      id: get_vars
      run: |
        echo '::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)'
        echo '::set-output name=DATE::$(date +'%D')'
      
    - name: Install Dependencies
      run: yarn install
      
    - name: Build Project
      run: yarn build

    - name: Push manifest change
      uses: EndBug/add-and-commit@v8
      with:
        add: fxmanifest.lua
        push: true
        author_name: Manifest Bumper
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'chore: bump manifest version to ${{ github.ref_name }}'

    - name: Update tag ref
      uses: EndBug/latest-tag@latest
      with:
        tag-name: ${{ github.ref_name }}

    - name: Bundle files
      run: |
        mkdir -p ./temp/mongodb
        cp ./{LICENSE,README.md,fxmanifest.lua} ./temp/mongodb
        cp -r ./dist ./temp/mongodb
        cd ./temp && zip -r ../mongodb.zip ./mongodb

    - name: Create Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      id: auto_release
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        title: '${{ env.RELEASE_VERSION }}'
        prerelease: false
        files: mongodb.zip

      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
